export enum ConfigEnvEnum {
  DATABASE_CONNECTION = 'DATABASE_CONNECTION',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_AUTH_SOURCE = 'DATABASE_AUTH_SOURCE',
  ORIGIN = 'ORIGIN',
  PORT = 'PORT',
  TZ = 'TZ',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRE = 'JWT_EXPIRE',
}

export type ConfigEnvType = {
  [key in ConfigEnvEnum]: string;
};
